---
title: "Intl Market"
---

## Groups

::: {.callout-note appearance="minimal" collapse="true"}
## Country Member List

|  Country 1  |  Country 2  |    Country 3   |  Country 4 |   Country 5   |
|-------------|-------------|----------------|------------|---------------|
|Chako, Ebissa|Batra, Joshua|Beaubien, Sydney|Adams, Emily|Connell, Sawyer|
|Dowler, Ben|Goldberg, Caleb|Hanson, Josh|Cruz, Owen|Friedrich, Holden|
|Fraser, Morgan|Gomez, Ariel|Hicks, Jackson|DiDomenico, Lena|Geiger, Amber|
|Hudson, Tyler|Hoke, Charlie|Lind, Sebbe|Huff, Jarrett|Heyman, Nick|
|Rohde, Harlen|Rudin, Amanda|Lum, Brandon|Miller, Jaden|Kelley, Sydney|
|Schaefer, Jack|Suchodolski, Brian|Marengo, John|Saito, Hikaru|Mcmullin, Rachel|
|Sinigaglia, Ludovico|Tran, Carter|Rushing, Cruz|Ulvenholm, Max|Patel, Eshan|
|Susumu, Ryuto|Tran, Derek|Schroeder, Giel|Vandamme, Vanny|Watters, Sarah|

|   Country 6  |    Country 7   |    Country 8   |  Country 9  |   Country 10  |
|--------------|----------------|----------------|-------------|---------------|
|Baeza, Simone |Clouser, Andrew |Asiamah, Daniel |Baros, Regan |Beekman, Tabor |
|Barnett, Max |Dadant, Evan |Barnett, Jennifer |Bendardaf, Ahmed |Brown, Zac |
|Cheng, Roger |Darmody, Riley |Colby, Piper |Cebula, Matthew |Burnett, Summer |
|Jones, Jacqueline |Joshi, Graham |Fletcher, Cody |Colombo, Louis |Conway, Logan |
|Montez, Austin |Murphy, Aidan |Girmay, Maerg |Lavin, Lila |Finley, Charlee |
|Rosario, Noah |Pruitt, Troy |Godby, Ethan |Novak, Carter |Kahawaii, Kate|
|Schwarzkopf, Parker |Shimizu, Rio |Henkle, Jake |Schreck, Aidan |Kameyama, Sota |
|Sherwood, Josh |Zarnick, Ethan |Kirby, Ethan |Truong, Brian |Schneiderman, Jacob |

:::

## Activity 01

### Game Set-Up

There are **10 groups (countries)** made up of 8 members each

In this game, we are seeing how **technological differences** across countries can impact outcomes.
Each country is tasked with producing as much as they possibly can given the time and resource constraints.

Each country is given an envelope with resources to produce paper shapes. 
Each shape has its own value and are "sold" in the market for a wealth transfer. 

**Shapes must adhere to specific measurements and the edges must be cut with scissors.**
**Any shape that is not measured properly or have a scissor-cut edge will be discarded.**

**YOUR SHAPES MUST HAVE YOUR COUNTRY NUMBER ON IT**


There are **three different type of countries** with the following **endowments**:

:::: {.columns .align-center}

::: {.column width="30%"}
**High Income** (2)

- x2 Scissors
- x2 Rulers
- x2 Protractors
- x2 Pencils
- x5 White Paper
- x5 $100 Notes
:::

::: {.column width="40%"}
**Middle Income** (5)

- x1 Rulers
- x2 Pencils
- x5 White Paper
- x5 $100 Notes
:::

::: {.column width="30%"}
**Low Income** (3)

- x2 Pencils
- x5 White Paper
- x5 $100 Notes
:::

::::

### Results

| Country | Circles | Rectangles | Triangle | Half | Cash Bills | Wealth | Share |
|---------|---------|------------|----------|------|------------|--------|-------|
| 1       | 2       | 5          | 0        | 1    | 13         | 4000   | 16.74%|
| 2       | 0       | 0          | 0        | 0    | 4          | 400    | 1.67% |
| 3       | 0       | 0          | 0        | 0    | 5          | 500    | 2.09% |
| 4       | 0       | 8          | 8        | 0    | 5          | 5300   | 22.18%|
| 5       | 0       | 15         | 0        | 0    | 0          | 4500   | 18.83%|
| 6       | 0       | 10         | 0        | 0    | 8          | 3800   | 15.90%|
| 7       | 0       | 0          | 13       | 0    | 0          | 3900   | 16.32%|
| 8       | 0       | 0          | 0        | 0    | 5          | 500    | 2.09% |
| 9       | 0       | 0          | 0        | 0    | 5          | 500    | 2.09% |
| 10      | 0       | 0          | 0        | 0    | 5          | 500    | 2.09% |
| **Total** | **2** | **38**     | **21**   | **1** | **50** | **23900** | **100%** |

There were a total of **112** shapes that met the necessary criteria. 

From the original raw resources and the total $5000 in cash, all countries produced a total of **$23900** in welfare (goods + money).

24 total cutouts were rejected: 9 rectangles, 4 circles, 11 triangles. 
This totals **$8000** in lost wealth. 

### Observations

The easiest shape to produce was the **triangle** followed by a **rectangle**.
It makes sense that countires specialized in producing these shapes due to the available technology. 
The one nation that was able to produce **circles** was likely the only nation that had a compass. 
This makes sense given that the most common technology were rulers. 

Unsurprisingly, wealth was concentrated in a few countries. 
This can be primarily explained through the initial endowment of technology. 
Some of the middle-income countries were able to trade and produce in a surprising way, closely matching wealthy nations. 

The data also suggests that poor countries either gave up, or were not able to trade for the necessary tools. 

Rather than trading goods, which everyone was aware of the international market price, countries traded their resources (paper) and techonology (tools). 
Something that actually happens in the real world is the trade of intermediate goods, which are input factors necessary in production. 

## Activity 02

### Game Set-Up

The class is divided into two countries, country X and country O.

In this game we are observing how tariffs may impact trade volume and behave as obstacles.
Each student is asked to rank all possible Dum-Dum flavors (16 total) from their most favorite to their least. 
They are then randomly given 3 Dum-Dums. 
Each student then counts the value of their initial bundle, based off their individual rankings. 

Students are then allowed to trade with each other. 
This can be either within country or across countries. 
There are two rounds of trading, with the random draw being completed at the start of each round. 
Each round is roughly of 5 to 7 minutes in length. 

In the first round, there are tariffs that a citizen from country O must pay if they trade with someone from country X.
The tariff takes form of a tic-tac-toe game. 
It does not matter who wins or loses. 
Once the game is complete, both students **must** go to the instructor to verify the game was completed, both students have written their names down on the game, and be signed by the instructor.
Once it is signed, they can now trade with each other. 
The objective of the tariff is to present a non-monetary obstacle to trading efficiency. 
While they are playing and getting their tariff verified, they are foregoing any other possible trades in the time spent. 

In the second round, there are **no tariffs** which allows for free trade within and across borders. 
In theory, this should permit for more trade and a more efficient allocation of bundles. 

### Results

The ranking of Dum-Dum flavors (on average) are as follows:

| Flavor         | Ranking (Avg) |
|:---------------:|:--------------:|
| blue raspberry | 12.84        |
| strawberry     | 10.25        |
| cherry        | 9.69         |
| peach-mango   | 9.16         |
| root beer     | 9.09         |
| sour apple    | 9.07         |
| cotton candy  | 8.67         |
| watermelon    | 8.47         |
| lemon lime    | 8.22         |
| pineapple     | 7.91         |
| fruit punch   | 7.85         |
| cream soda    | 7.55         |
| orange        | 7.16         |
| bubblegum     | 7.09         |
| butterscotch  | 6.6          |
| grape         | 6.33         |

The results of each round are:

|   Statistic  | Round 1 | Round 2 | R2 - R1 |
|--------------|:-------:|:-------:|:-------:|
| Initial (Avg) | 27.76  | 25.76   | -2      |
| Initial (Std) | 9.37   | 8.09    | -1.28   |
| Final (Avg)   | 40.73  | 41.09   | 0.36    |
| Final (Std)   | 6.34   | 6.65    | 0.31    |
| Trades (Avg)  | 2.73   | 3.38    | 0.65    |
| Gain per Trade   | 4.75   | 12.15   | 7.4     |

### Observations

The data suggests that there were no large differences in the value of the starting bundle and students were able to maximize their bundle value at similar levels.

However, the number of trades does increase (on average) which is expected as there are less obstacles from Round 1 to Round 2. 

Most surprising is the **efficiency** gains when tariffs are removed.
Students were able to find ideal trading partners to maximize gains from each trade. 
This is evidenced in gain per trade value increasing from 4.75 in Round 1 to 12.15 in Round 2.

As anecdotal evidence, trading in Round 2 eased and finished nearly 2 minutes before the time limit. 

<!--
## Activity 03

### Game Set-Up

### Results

### Observations
-->