project:
  type: website
  render:
    - "*.qmd"
    - "*.md"
  output-dir: docs 
  

website:
  title: "EC 380 - International Econ"
  favicon: UO-icon.png
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: Slides/lectures.qmd 
        text: Slides
      - href: Readings/articles.qmd
        text: Readings
      - href: Assignments/list.qmd
        text: Homework
      - href: about.qmd
        text: About Me

format:
  html:
    theme: 
      - cosmo 
      - styles.scss
    toc: true



