---
title: "Home"
---

## Syllabus

```{=html}
<details>
  <summary>Winter 2025 Syllabus PDF</summary>
  <a class="btn btn-primary btn-lg cv-download" href="Documents/Syllabus/Syllabus.pdf" target="_blank">
    <i class="fa-solid fa-file-arrow-down"></i>&ensp;Download
  </a>
  <div class="embed-container">
    <iframe src="Documents/Syllabus/Syllabus.pdf" style="border: 0.5px" height="1000" width="800"></iframe>
  </div>
</details>
```

## Winter 2025 Class Details

:::: {.columns}
:::{.column width="50%"}

**Instructor:** Jose Rojas-Fallas

**Email:** jrojas2@uoregon.edu

**Office Hours:** Wed 09:00 to 11:00 am in PLC 525
:::

::: {.column width="50%"}

**Class Location:** Straub 245

**Class Day & Time:** Mon & Wed - 2:00 - 3:20pm

**Textbook/Readings:** [Check Here](Readings/articles.qmd)
:::

::::

### Course Grade Breakdown

For more details, read the [Syllabus](Documents/Syllabus/Syllabus.pdf) above


| Assignment   | Grade Weight  | 
|:------------|:------------:|
| Problem Sets (x5) | **25%** |
| Quizzes (x4) | **10%** |
| Midterm Exam | **30%** |
| Final Exam | **30%** |
| International Market Game | **5%** |

### Tentative Schedule

| **Week** |  **Reading** |    **Topic**    | **Assignments** |
|:--------:|:------------:|:---------------:|:---------------:|
|    01    | [Chapter 01](Readings/articles.qmd#chapter-01-(p.-24---37)) & [Chapter 03](Readings/articles.qmd#chapter-03-(p.-64---85)) | [Ricardian Model](Slides/lectures.qmd#ricardian-model) | - | 
|    02    | [Chapter 04](Readings/articles.qmd#chapter-04-(p.-87---114))  |    [OH Model](Slides/lectures.qmd#ho-model)     | [Problem Set 01](Assignments/list.qmd#ps01-(due-jan.-15-before-lecture-on-canvas)) & [Quiz 01 Due](Assignments/list.qmd#quiz-01-(due-jan.-15-before-lecture-on-canvas)) |
|    03    | [Articles](Readings/articles.qmd#course-literature)   | [Issues & Empirics](Slides/lectures.qmd#issues--empirics) |  [Problem Set 02](Assignments/list.qmd#ps02-(due-jan.-22-before-lecture-on-canvas) Due) |
|    04    | [Chapter 06](Readings/articles.qmd#chapter-06-(p.-139---158))  | [Trade Policy](Slides/lectures.qmd#trade-policy) | [Problem Set 03](Assignments/list.qmd#ps03-(due-jan.-29-before-lecture-on-canvas)) & [Quiz 02 Due](Assignments/list.qmd#quiz-02-(due-jan.-29-before-lecture-on-canvas)) |
|    05    | [Practice](Assignments/list.qmd#practice-midterm)   | Midterm Review | Midterm | 
|    06    | [Chapter 12](Readings/articles.qmd#chapter-12-(p.-298---310)) | [Globalization](Slides/lectures.qmd#globalization--international-crises) & [Intl. Crises](Slides/lectures.qmd#globalization--international-crises) | - |
|    07    | [Chapter 09](Readings/articles.qmd#chapter-09-(p.-206---231)) | [Balance of Payments I](Slides/lectures.qmd#part-one) [Balance of Payments II](Slides/lectures.qmd#part-two) | - |
|    08    | [Chapter 09](Readings/articles.qmd#chapter-09-(p.-206---231)) | [Exchange Rate (Long-Run)](Slides/lectures.qmd#exchange-rates) | [Problem Set 04](Assignments/list.qmd#ps04-(due-feb.-26-before-lecture-on-canvas)) & [Quiz 03 Due](Assignments/list.qmd#quiz-03-(due-feb.-26-before-lecture-on-canvas)) |
|    09    | [Chapter 10](Readings/articles.qmd#chapter-10) | [Exchange Rate (Short-Run)](Slides/lectures.qmd#exchange-rates) | - |
|    10    | [Chapter 13](Readings/articles.qmd#chapter-13-(p.-328---351)) & [Chapter 15](Readings/articles.qmd#chapter-15-(p.-382---407)) | [Regional Topics](Slides/lectures.qmd#regional-topics) | [Problem Set 05](Assignments/list.qmd#ps05-(due-mar.-05-before-lecture-on-canvas)) & [Quiz 04](Assignments/list.qmd#quiz-04-(due-mar.-12-before-lecture-on-canvas)) | 


## Acknowledgements

This class has been created using materials passed down by a former UO graduate student. 
Thank you [Phillip Economides](https://philip-economides.com){target="_blank"} for the invaluable help and support. 

Thank you to [Dante Yasui](https://github.com/dyasui){target="_blank"}, whose own class website inspired and helped me figure out how to properly code this one. 
