---
title: "Global Finance | Balance of Payments I"
subtitle: "EC 380 - International Economic Issues"
author: Jose Rojas-Fallas
date: last-modified
date-format: "YYYY"
format:
    revealjs:
        theme: [default, styles.scss]
        slide-number: true
        footer: "EC380, Lecture 07 | Balance of Payments I"
        preview-links: auto
        code-fold: FALSE
title-slide-attributes: 
  data-background-position: left
---

## Recap

[Previously]{.h}

- With globalization comes greater economic interdependence and larger risk of [contagion effects]{.hp} once crises crop up

[Today]{.h}

::: {.incremental}
- Explore the [system]{.hp} used to track country's international transactions

- Establish relationship between domestic investment, domestic savings, and international flow of goods, services, and financial assets

- Examine the consequences of [international indebtedness]{.hp}
:::

## Layout

There are [three separate accounts]{.hp} for the [Balance of Payments]{.hi}:

<br>

- [Current Account]{.h}

<br>

- [Capital Account]{.h}

<br>

- [Financial Account]{.h}

# Account Types {.inverse .note}

{{< include 071-account-types.qmd >}}

# Financial Account {.inverse .note}

{{< include 072-financial-account.qmd >}}

# Interdependence {.inverse .note}

{{< include 073-interdependence.qmd >}}

## Summary

[Recapping]{.h}

- Contents of Balance of Payments indicate net flows

- Financial Accounts should balance with Current + Capital

[Next time]{.h}

- Macroeconomy implications of BoP state

- International Debt considerations

- Investment Position

- Introduce Exchange Rates