---
name: national accounts
---

## National Accounts + Deficit

[National Income and Product Accounts (NIPA)]{.hp .align-center}

::: {.fragment}
[Gross Domestic Product (GDP):]{.hi}
Value of all final goods and services produced inside its borders during some time period
:::

::: {.fragment}
[Gross National Product (GNP)]{.hi} 
Value of all final goods and services produced by the labor, capital, and other resources of a country, [regardless of where production occured]{.hp}
:::

::: {.fragment}

\begin{align*}
    GNP = GDP &+ \text{Foreign Income Received} \\ 
    &- \text{Income Paid to Foreigners} \\ 
    &+ \text{Foreign Tranfers Received} \\ 
    &- \text{Transfers Paid to Foreigners} 
\end{align*}

:::

---

## National Accounts + Deficit

We can write our [GNP]{.hi} formula as:

$$
    GNP = GDP + (\text{Net Primary Income} + \text{Net Secondary Income})
$$

::: {.fragment}
From standard macro models we know that:

$$
    GDP = C + I + G + X - M
$$
:::

::: {.fragment}
\begin{align*}
    \text{GNP} = C + I + G + \underbrace{(X - M + \text{Net Primary} + \text{Net Secondary})}_{\text{Current Account}}
\end{align*}
:::

::: {.fragment}
[GNP is also the value of income received]{.hp}
:::

---

## National Accounts + Deficit

[GNP is also the value of income received]{.hp}

::: {.fragment}
Individuals may [consume income (C)]{.hp}, [save it (S)]{.hp}, or use it to [pay taxes (T)]{.hp}

In reality, we do a combination of all three
:::

::: {.fragment}
$$
    \text{National Income} = GNP = C + S + T
$$
:::

::: {.fragment}
If we set output equal to income:

$$
C + I + G + CA = C + S + T \;\; \Rightarrow \;\; I + G + CA = S + T
$$
:::

::: {.fragment}
$$
    S + (T - G) = I + CA
$$

Supposing we have a [balanced government budget]{.hp}, savings are equal to total investment in the country plus current account net flows
:::

---

## National Savings

A nation's savings (private plus public) are divided into [two uses]{.hp}

[Source of funds for]{.h} [domestic investment]{.hp}

::: {.incremental}
- If government budgets are in deficit, overall Left-hand side goes down, and [all else being equal]{.h}, investment falls
- Government budget surplus increases the funds available for investment
:::


[Source of funds for]{.h} [foreign investment]{.hp}

::: {.incremental}
- If CA surplus, its national savings exceed domestic investment, and the surplus finances the purchase of domestic goods by foreign buyers. 
- In return, the domestic economy acquires foreign financial assets, as it effectively lends to the rest of the world.
:::

---

## National Savings

Recall [financial account]{.hp} reflects the same amount of lending or borrowing as [CA]{.h}

::: {.fragment}
If [$CA < 0$]{.h}, financial account features net borrowing greater than net acquisition of financial assets (lending, or financial outflows)
:::

::: {.fragment}
- Negative current account $\Rightarrow$ net borrowing in the financial account, inflow of financial capital
- Surplus countries provide savings to the rest of the world, enabling sale of more goods abroad than they buy
- Financial capital outflow is investment because it involves acquisition of assets that are expected to pay a future return
:::

---

## National Savings

Because of this, another name for the [current account balance]{.hp} is [net foreign investment]{.hp}

::: {.fragment}
A negative current account balance means that foreigners are acquiring more assets in the home country than the home country’s residents are acquiring abroad.
:::

::: {.fragment}
- The US has had a [CA deficit]{.hp} every year since 1981. 
Financial crisis of 2007-2009 had a dramatic effect on savings, investment, and government budgets

- Savings rose, investment fell.
Federal budgets fell into large deficits.
Falling import levels represented an improvement in the [CA balance]{.hp}
:::