---
name: current accounts
---

## Current Account Deficit

All of this begs the question:

[Are Current Account Deficits Harmful?]{.hp .align-center}

::: {.fragment}
The relationship between the current account balance, investment, and total national savings is an [identity]{.hp}

It does not tell us why economy runs CA deficit or surplus
:::

::: {.fragment}
$$
    S + (T - G) = I + CA
$$

We cannot say CA is in deficit because [saving is too low]{.hp} any more than we can say it is because [investment is too high]{.hp}
:::

---

## Current Account Deficit

<br>

It is a general tendency in the media and public discourse to interpret a [CA deficit]{.hp} as a sign of weakness and harmful to the nation's welfare

<br>

::: {.fragment}
A deficit [enables more investment]{.hp} than would be possible otherwise (higher investment $\Rightarrow$ higher living standards)
:::

<br>

::: {.fragment}
Capital inflows associated with current account deficits can be thought of as an [implicit vote of confidence by foreigners]{.hp}
:::

---

## Current Account Deficit

For example, between 1980 and 1991, Japan invested over $25 billion of [trade surplus]{.hp} in US manufacturing

By the early 90s, they were employing more than 100,000 US workers. 
Investment came during major domestic layoffs.

Japanese firms acquired capital, built new plants with Japanese savings

During the US CA deficits of the 1990s, foreign investors continued to pour in capital, enabling increased productivity despite declining savings rate

::: {.fragment}
[CA deficit enabled more investment than was possible otherwise]{.hp .align-center}
:::

---

## Current Account Deficit

[CA deficits can also generate problems]{.hp .align-center}

::: {.fragment}
Capital inflows that occur with CA deficit increase the stock of foreign-owned assets in the home country

::: {.incremental}
- Home country is now far more exposed to [foreign policy/foreign business cycle conditions]{.h}
- A sudden change in investor expectations about the home country's future or their country's prospects can lead to a [sudden surge in capital outflows]{.hp}
- In a [worst-case scenario]{.hp}, capital flight is followed by a depletion of international reseves and a financial crisis
:::

:::

---

## Current Account Deficit

This is an experience shared by a number of developing countries since the 1980s

::: {.fragment .small}
Deficits allow countries to invest more, huge opportunity for developing countries where investment capital is scarce

International financial crises, like biological diseases, tend to be [contagious]{.hp}
:::

::: {.fragment .small}
> When Mexico slipped into the [peso crisis]{.h} in late 1994 and early 1995, economists began to write about a "Tequila Effect" on Latin America. 

> When Thailand's currency lost a large share of its value in 1997, media reported the crisis spreading across East Asia.

> In both cases, the size of the CA balances were not good predictors of whether it was drawn into the crisis
:::