---
name: globalization perspectives
---

## Effects of Globalization

We have covered a lot of this so far, having reviewed the theory and some empirical literature. 

To summarize what we have seen and its relation to [globalization]{.hp}:

::: {.fragment}
- More goods at lower prices through exploiting comparative advantages

- Scaled up enterprises, multinationals, allowing for large-scale tchnological developments

- Better quality and variety of goods, as a result of increased product-level competition

- Supports new job opportunities but also contributes to job displacement
:::

---

## Globalization & Jobs

It does [not significantly change]{.h} the total number of jobs in the economy

- Job numbers are primarily driven by business cycles, monetary and fiscal policies

::: {.fragment}
Some [Peterson Institute studies]{.hp} have found that 156,250 US manufacturing jobs lost on net each year between 2001 and 2016 from expanded trade in manufactured goods

This represents [less than 1%]{.hp} of the workers laid off in a typical year
:::

---

## Globalization & Jobs

[Low-wage workers]{.hp} in certain regions are most affected. 
Many of them also face lower earnings or have dropped out of the workforce

::: {.fragment}
[Bigger factors]{.hp} than trade that drive job displacements are labor-saving technologies, like automated machines and artificial intelligence
:::

::: {.fragment}
Better-paying positions have opened up in manufactured exports

- Especially in [high-tech areas]{.hp}, such as computers, chemicals, and transportation equipment
:::

---

## Globalization & Income

There has been a decline in global income inequality but [it has increased in the US]{.hp}

Globalization helped narrow inequality between poorest and richest people in the world, with the number of people living in [extreme porverty]{.h} having been cut in half since 1990

Most scholarly work holds that globalization contributed marginally to rising US wage inequality (somewhere from 10% to 20%)

---

## Globalization, Income, and the US

[Leading Explanation:]{.h} Technology has reduced demand for low and middle-wage workers and increased demand for high-skilled, high-wage workers

Countries exposed to globalization have alleviated inequality to different degrees through tax and welfare systems

The US has done [the least among advanced economies]{.hp} to mobilize government policies [to reduce inequality]{.hp}

---

## Globalization & Entry of Firms into US 

[Foreign-owned companies]{.hp} that do business in the US have hired Americans at a [faster rate than US private employers]{.h} between 2007 and 2015

<br>

::: {.fragment}
One in five American manufacturing workers is now employed by a foreign-owned company operating in the United States

They also pay better, do [more research and development, export more, and invest more]{.h} than the average US firm
:::

::: {.fragment}
[The same is true of US firms that invest abroad]{.hp}

[It is more of an international firm advantage story]{.hp}
:::
---

## Public Views

[How do Americans feel about Globalization?]{.hp .align-center}

::: {.incremental}
- Listening to political debates around this can cause confusion

- Not surprisingly, polls vary widely depending on how and when the question is asked

- Can be a hard sell to the general public because the benefits are widely distributed and not easily understood, while the costs are more straightforward to visualize
:::

::: {.fragment}
[All of this confusion is not helped by the US's inaction at helping temporarily displaced workers]{.hp .align-center}
:::

---

## Public Views

An [OECD Study]{.hp} suggests policymakers have done [little to help workers adjust]{.hp} at a time when the [wealthiest Americans have gained the most]{.h}

::: {.fragment}
In general, [younger people]{.h} are [more supportive of free trade]{.hp}, as most have never known a world without the current system
:::

<br>

::: {.fragment}
Before 2016, [Republicans]{.h} generally [favored US trade deals]{.hp} and [Democrats]{.h} generally [voted against them]{.h}

The first Trump administration canceled the TPP, threatened withdrawing from NAFTA, the Korea-US Free Trade Agreement (KORUS), and the WTO

They also pushed for more power to impose tariffs
:::

---

## Policy Action

Some crucial areas that economists have proposed the United States focus on are:

- Invest in better and more inclusive education

- Give all displaced workers sufficient financial and administrative support

- Address growing income inequality thorugh the tax system and spending programs

- Make sure the healthcare system doesn ot impede workers from finding new jobs

- Coordinate with allies to confront trade abuses