---
name: tariffs
---

## Tariff Analysis

So far we have examined transitions from [autarky]{.hp} into [free trade]{.hp} 

::: {.fragment}
In practice, even the most seemingly open economies will have some kind of measures in place that regulate the manner in which goods are traded internationally
:::

::: {.fragment}
Take something that seems like a good cause: [quality control]{.h}

Restrictions introduce [quality control]{.hp} over goods entering the country but have the added effects of [limiting volume of trade]{.hp} that would otherwise occur

[Why?]{.hi .align-center}
:::

::: {.fragment}
Trade policy, like any other form of interverntion, introduces [costs for firms]{.hp}, which get passed on to consumers. 
Some consumers will [switch to domestic goods]{.hp}
:::

---

## Tariff Analysis

To understand how tariffs may affect outcomes, we have to understand the components and start from the beginning 

<br><br>

::: {.incremental}
- [Consumer Demand Curve]{.hi}
- [Producer Supply Curve]{.hi}
- [Consumer and Producer Surplus]{.hi .align-center}
:::

---

## Consumer Demand Curve

- Demand is mapped by the [marginal wilingness of individuals to pay]{.h} for a good at a given price

::: {.incremental}
- At a particularly high price, only a small number of individuals would purchase
- [As price falls]{.hp}, the good enters into a greater pool of individuals' marginal willingness to pay, leading to [quantity demanded rising]{.hp}
:::

::: {.fragment}
Therefore, we assume a [negative relationship]{.hi-red} between market price and [quantity demanded]{.h}
:::

--- 

## Producer Supply Curve

- When the market price is particularly low, only a small number of firms can afford to service the market

::: {.fragment}
- As [prices rise]{.hp}, the [quantity supplied to the market increases]{.hp}, given that the greater associated revenue makes business profitable for an increasing number of firms
:::

::: {.fragment}
Therefore, we assume a [positive relationship]{.hi-green} between market price and [quantity supplied]{.h}
:::

---

## Consumer and Producer Surplus

When we combine these two strands of intuition we arrive at:

::: {.incremental}
- Demand curve for a given good is [downward sloping]{.hi-red}
- Supply curve for a given good is [upward sloping]{.hi-green}
:::

::: {.fragment}
As per standard economic theory, the market will produce where supply meets demand
:::

::: {.incremental}
- Any difference between [marginal willingness to pay]{.h} and [price]{.h} represents [surplus for the consumer]{.h}

- Any difference between [marginal willingness to receive]{.hi} and [price]{.hi} represents [surplus for the producer]{.hi}
:::