---
name: observing protectionism
---

## Seeing is Believing

Many non-tariff measures function similarly to the quotas we have considered

Economists divide these into two categories:

<br>

:::: {.columns}

::: {.column width="50%"}
[Tariffs]{.hi .align-center}
:::

::: {.column width="50%"}
[Non-Tariff Barriers (NTBs)]{.hp .align-center}
:::

::::

<br>

::: {.fragment}
- [NTBs]{.hp} can be subdivided into quotas and non-tariff measures
- They are often hidden, in that they are not presented as barriers, even though they contribute a similar influence
:::

---

## Observing Protectionism - Example {.small}

One common example is with respect to [chlorinated chicken]{.hp} imports from the US to UK

::: {.incremental}
- This is poultry that has been washed with chlorine 
- Done to treat high levels of bacteria, a symptom of poor hygiene and low animal-welfare conditions
- Practice of chlorine washing chicken is common practice in the US poultry industry, but banned in the UK
- Higher hygiene and animal welfare standards make it so that chlorine washing are not necessary
:::

::: {.fragment}
[Is this a legitimate NTB?]{.hp}

It's hard to tell if they are directly created to target trade or if its solely for domestic standards which happen to have trade-related effects
:::
