---
name: currency exchange
---

## Currency Exchanges

All of the work on globalization and interconnectedness begs the question:

[Why hold other currencies?]{.hp}

::: {.fragment}
We will argue there are [three reasons]{.h}
::: 

::: {.fragment}
[ 1) Enable trade and investment purposes]{.hi}
:::

::: {.fragment .small}
> Traders (importers and exporters) and investors routinely transact in foreign currencies, either receiving or making payments in another country's currency. 

> Tourists are included in this category because they have to participate in foreign exchange in order to buy foreign goods and services
:::

---

## Currency Exchanges

All of the work on globalization and interconnectedness begs the question:

[Why hold other currencies?]{.hp}
We will argue there are [three reasons]{.h}

[2) Interest Rate Arbitrage]{.hi}

::: {.fragment .small}
> Arbitrage conveys the idea of buying something where it is relatively cheap and selling it where it is relatively expensive

> Arbitrageurs borrow money where interest rates are relatively low and lend it where rates are relatively high
:::

::: {.fragment .small}
This keeps interest rates from diverging too far and also constitutes one of the primary linkages between national economies
:::

---

## Currency Exchanges

All of the work on globalization and interconnectedness begs the question:

[Why hold other currencies?]{.hp}
We will argue there are [three reasons]{.h}

[3) Speculative Action]{.hi}

::: {.fragment .small}
> Speculators are businesses that buy or sell a currency because they expect its value to rise or fall

> They have no need for foreign exchange to buy goods/services or financial assets; rather, they hope to realize profits or avoid losses through correctly anticipating changes in a currency's market value
:::

::: {.fragment .small}
If speculators view currency as overvalued, they will sell it and drive down its value.
:::

::: {.fragment .small}
If they guess wrong, however, they can lose a lot of money
:::

---

## Currency Speculation

This is a point of contention

Not everyone agrees that currencies should be traded speculatively, due to [panics these actions can trigger en-masse]{.hp}

::: {.fragment}
Speculation against currency can be [destabilizing]{.hp} and sometimes lead to grossly over- or under-valued currency which is a major problem for that country
:::

---

## Currency Exchanges

There are [three main participants]{.h} in foreign currency markets:

::: {.incremental}
- [Retail Customers:]{.hp}

    - Includes any firms/individuals that hold foreign exchange to engage in purchases, to adjust their portfolios, or to profit from expected future currency movements

    - Usually buy and sell through a commercial bank
:::

---

## Currency Exchanges

There are [three main participants]{.h} in foreign currency markets:

- [Retail Customers]{.hp}

::: {.incremental}
- [Commercial Banks:]{.hp}

    - Hold inventories of foreign currencies as part of services offered to customers.
    Usually have relationship with several foreign banks where they hold their balances of foreign currencies

    - When a surplus accumulates or a shortage of funds develops, the banks trade with each other to adjust their holdings

    - Not very common for US banks to trade currency with foreign banks, they tend to use [foreign exchange brokers]{.hp}
:::

---

## Currency Exchanges

There are [three main participants]{.h} in foreign currency markets:

- [Retail Customers]{.hp}

- [Commercial Banks]{.hp}

::: {.incremental}
- [Foreign Exchange Brokers:]{.hp}

    - Middlemen between buyers and sellers that do not usually hold foreign exchange

    - Brokers can also serve as agents for [central banks]{.hp}
:::

---

## Foreign Exchange Brokers

Here's how it works:

::: {.incremental}
- An individual or firm that needs foreign exchange calls its bank
- The bank quotes a price at which it will sell the currency 
- The price is based on either:
    - Bank having an account with the bank in the foreign country where currency is used
    - Rate from foreign exchange broker
- Broker keeps track of buyers and sellers of currencies and acts as deal maker
:::