---
name: banking crises
---

## Banking Crises

The primary role of a bank is to provide intermediation between [savers]{.hp} and [borrowers]{.hp}

::: {.incremental}
- Banks pool deposits and make them available to would-be investors that need loans

- A functional banking system is necessary to bolster investment by firms and homeowners
:::

---

## Interbanking Lending Channels

[Banking systems]{.h} are reliant on interbanking lending channels

<br>

[Why?]{.hp .align-center}

::: {.fragment}
- No bank has enough money/cash to reedem every $ of deposits it maintains

- Some $ of bank's liabilities returned to depositers every day

- In cases where a bank lacks cash, it can engage in [interbank lending]{.hp}
:::

::: {.fragment}
> A bank is considered [insolvent]{.hp} if, [even after completely liquidizing its assets]{.hi}, it [cannot repay]{.hp} its outstanding liabilities owed to creditors
:::

---

## Banking Crises

During a [banking crisis]{.hp}, an abnormally large % of borrowers fail to meet debts

::: {.fragment}
- Bank assets may suddenly deteriorate

- Depositers may trigger a [run on banks]{.hp}
:::

::: {.fragment}
If numerous banks struggle meeting obligations to their depositors, there can be a major loss of savings

Remaining savings can be lost, [causing households to reduce consumption]{.h}. 
This can lead to ripple effects throughout the economy
:::

::: {.fragment}
> [Note: Most countries offer deposit insurance. But other types of financial products are still vulnerable.]{.note .hi} 
:::