---
name: vulnerabilities
---

## Vulnerabilities

[What are the origins of a given international crisis?]{.hp}

<br>

::: {.fragment}
Could be due to:

- Macroeconomic imbalances

- Capital flow volatility
:::

::: {.fragment}
Long-run underlying issues for the domestic economy may lead to over-reliance of foreign debt and over-leveraged credit status across households

Can be the result of either of these two scenarios
:::

---

## Economic Imbalances

Macro-imablances can be attributed to: 

:::: {.columns}

::: {.column width="50%"}
- Large budget deficits
- Large current account deficits
- Overinflated exchange rates
:::

::: {.column width="50%"}
- Unsustainable private sector
- Speculative property bubbles
:::

::::

::: {.fragment}
Usually, these issues occur simulataneously, further complicating matters of unravelling macroeconomic imbalances
:::

::: {.fragment}
[Poor fiscal policy]{.hp} may lead to major public debt and high domestic inflation
:::

::: {.fragment}
Doubt in government ability may result in government bond yields needing to rise to continue accessing foreign debt. 
Which limits the ability of the government to service the economy
:::

---

## Volatile Capital Flows

As [Warnock & Forbes (2012)]{.hii} highlight, there is an ebb-and-flow to capital investment

::: {.fragment}
During good times, capital is situated in developed economies and accruing returns based on strong economy performance and high interest rates

When developed economies enter recession, central banks [lower interest rates]{.hp} and domestic economies see a [slump in consumption]{.hp}
:::

::: {.fragment}
Capital investors [migrate]{.hp} to low-income/emerging economies until resurgence in developed country economy

These volatile movements of large sums of capital within these transition periods can be [highly costly for the emerging host countries]{.hp}
:::

---

## Contagion

Particularly strong cases of interbank lending across countries make these spillovers of domestic shocks into foreign countries become amplified

As the world becomes [more globalized]{.hi}, financial interlinkages become stronger

Local shocks are increasingly likely to trigger worldwide repercussions due to greater degree of [financial interdependence]{.hp}

<br>

::: {.fragment}
[This aspect of crises determines the scale of how "international" or "cross-country" a given crisis will be]{.hp .align-center}
:::

---

## Crisis Control (CC)

The financial sector has always been a concern for policymakers, due to the [too big to fail mindset]{.hp}

::: {.fragment}
- Bailouts of banks can protect the economy, but greater risks offer greater returns

- Encourages banks to become large enough to [force bailouts]{.hp} in between episodes of them over-leveraging themselves
:::

::: {.fragment}
This is known as the [Moral Hazard Problem]{.hp}. 
Where bankers are able to transfer high risks to the government and taxpayer

Lets consider three measures a country can take to reduce exposure to financial crises

:::: {.columns}

::: {.column width="35%"}
- [Exchange Rate Policy]{.h}
:::

::: {.column width="30%"}
- [Capital Controls]{.h}
:::

::: {.column width="35%"}
- [General Policies]{.h}
:::

::::

:::

---

## CC: Exchange Rate Policy

Avoidance of a [crawling peg exchange rate system]{.hp} is often recommended

- [Crawling Peg]{.hp} involves fixing the exchange rate to a major world currency 

$$
    R_{r} = R_{n} (P^{*}/P)
$$

::: {.fragment .small}
- Regular devaluation of currency to stablize [real exchange rate $(R_{r})$]{.hp} in country with higher inflation than foreign partner
- Requires monetary authority to restrict money creation, making it [anti-inflationary]{.hp}
- When a government under this regime announces a change in the system (away from [crawling peg]{.hp}), it runs the risk of losing its credibility
:::

---

## CC: Capital Controls

Capital volatility can be addressed by limiting how much capital enters and exits the country

::: {.fragment}
- Many economist believe that free movement of capital is ideal as it allows financial capital to flow wherever the return is highest
- Those against it claim that this is only a theoretical concept and has not been shown in the data
:::

::: {.fragment}
- Capital flow restrictions are imposed by limiting transactions that are part of the financial account of the balance of payments
- As a general rule, restrictions on inflows are seen as more workable than restrictions on outflows
:::

---

## CC: General Policies

The solution to fiscal/monetary crises are quite simple:

- Fix the thing that is broken

::: {.fragment}
But the solution may simply not be politically feasible

- A budget deficit reduction may stem reserve loses and lower financial exposure

- Interest rate appreciation may boost demand for domestic currency, further helping

These are simple but difficult to stomach
:::

::: {.fragment}
In the worst of cases, a policy action may turn a relatively small problem into a full-blown depression
:::