---
name: cip and uip
---

---

## CIP and UIP

<br>

[Covered Interest Parity (CIP)]{.h}

::: {.fragment}
- Assume the investor has [perfect foresight]{.hp} such that $E(F) = F$
::: 

<br>

[Uncovered Interest Parity (UIP)]{.h}

::: {.fragment}
- Assume investor accepts risk involved and purchases with E(F) in mind
:::

---

## FX Market: CIP

Investors will trade until returns from either bond equalize, and [all arbitrage opportunities are exhausted]{.hp}

::: {.fragment}
$$
    \text{CIP: } (1 + i) = (1 + i^{*}) \dfrac{F_{\text{USD/EUR}}}{R_{\text{USD/EUR}}}
$$
:::

::: {.fragment}
In that case, investors are [indifferent]{.hp} between either bond since their real returns are the same

This allows us to pin down the $F$ necessary to achieve [CIP]{.h}
:::

::: {.fragment}
$$
    F_{\text{USD/EUR}} = R_{\text{USD/EUR}} \times \dfrac{1 + i}{1 + i^{*}}
$$
:::

---

## FX Market: UIP

This alternative method of investment allows us to determine how spot rates are established

::: {.fragment}
The no-arbitrage condition for [UIP]{.h} is written as:

$$
    \text{UIP : } (1 + i) = (1 + i^{*}) \dfrac{E(F)_{\text{USD/EUR}}}{R_{\text{USD/EUR}}}
$$
:::

::: {.fragment}
This lets us pin down the $R$ necessary to satisfy [UIP]{.h}

$$
    R_{\text{USD/EUR}} = E(F)_{\text{USD/EUR}} \times \dfrac{1 + i^{*}}{1 + i}
$$

We can calculate today's spot rate if we know market expected exchange rate and tehse two respective interest rates
:::

---

## FX Market: CIP & UIP {.small}

Taking both our previous equations, and dividing one into the other on [both sides]{.h}:

$$
    \text{CIP: } (1 + i) = (1 + i^{*}) \dfrac{F_{\text{USD/EUR}}}{R_{\text{USD/EUR}}}
$$

$$
    \text{UIP : } (1 + i) = (1 + i^{*}) \dfrac{E(F)_{\text{USD/EUR}}}{R_{\text{USD/EUR}}}
$$

::: {.fragment}
$$
    \Rightarrow 1 = \dfrac{F_{\text{USD/EUR}}}{E(F)_{\text{USD/EUR}}}
$$  
:::

::: {.fragment}
Under the assumption of both types of investors (risky and riskless) exhausting all arbitrage opportunities, expected exchange rates should be equal to forward exchange rates
::: 