project:
  type: book

book:
  title: "International Economic Issues Workbook"
  subtitle: "The Fun Stuff About Trade"
  author: "Jose Rojas-Fallas"
  date: "7/19/2024"
  favicon: globe-icon.png
  chapters:
    - index.qmd
    - game/organization.qmd
    # - slides/003-trade-overview.qmd
    #     parts:
        # - game/round-1.qmd
        # - game/round-2.qmd
        # - game/round-3.qmd
        # - game/round-4.qmd
        # - game/round-5.qmd
#    - Gerber/CH1/ch1-summary.qmd
#    - Gerber/CH3/ch3-summary.qmd
#    - Gerber/CH4/ch4-summary.qmd
#    - Gerber/CH6/ch6-summary.qmd
#    - Gerber/CH8/ch8-summary.qmd
#    - Gerber/CH10/ch10-summary.qmd
#    - Gerber/CH12/ch12-summary.qmd
#   - Gerber/CH15/ch15-summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

