project:
  type: book

book:
  title: "International Economic Issues Workbook"
  subtitle: "The Fun Stuff About Trade"
  author: "Jose Rojas-Fallas"
  date: "7/19/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

