# Course Objectives {.unnumbered}

This is a companion book I've written for my EC 380 International Trade course. EC 380 is an introductory course to international economics undergraduates. I do not expect us to become experts in the field in just 10 weeks.

The goal is to give you enough knowledge that you can spot the bullshit when you read the news, listen to a podcast, or talk with someone. The goal is to make you comfortable with talking about the complexity of international economics.

Ideally, by the end of the course you will have:

-   Understood what comparative advantage means for international trade
-   Understood why countries specialize and trade
-   Understood why trade is generally good, and understand how it can be bad

# International Market Game

What better way to learn than to play a game?

Throughout the term we will create our own international economy. The objective is to experience what markets do and how different agents make decisions. The theory will teach us what ***should*** happen, but theory is just theory.

We will test theory and learn by doing.
